import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "p1",
    name: "دمبل قابل تنظیم پرو سری",
    price: 62_000_000,
    image: "/assets/latest-dumbbells.jpg",
    engravable: true,
    category: "قدرتی",
    discipline: "پاورلیفتینگ",
    material: "چدن",
    weightBucket: "۱۵ تا ۳۰ کیلوگرم",
  },
  {
    id: "p2",
    name: "کتل‌بل المپیک",
    price: 16_000_000,
    image: "/assets/cat-freeweights.jpg",
    engravable: true,
    category: "قدرتی",
    discipline: "وزنه‌برداری المپیک",
    material: "چدن",
    weightBucket: "۱۵ تا ۳۰ کیلوگرم",
  },
  {
    id: "p3",
    name: "دستگاه روئینگ حرفه‌ای",
    price: 120_000_000,
    image: "/assets/cat-rowers.jpg",
    category: "هوازی",
    discipline: "تمرین عملکردی",
    material: "فولاد",
    weightBucket: "بالای ۳۰ کیلوگرم",
  },
  {
    id: "p4",
    name: "تشک یوگا استودیو",
    price: 4_800_000,
    image: "/assets/latest-recovery.jpg",
    category: "ریکاوری",
    discipline: "یوگا",
    material: "چوب پنبه",
    weightBucket: "کمتر از ۵ کیلوگرم",
  },
  {
    id: "p5",
    name: "ست کش مقاومتی کربن",
    price: 7_200_000,
    image: "/assets/cat-cross.jpg",
    category: "لوازم جانبی",
    discipline: "تمرین عملکردی",
    material: "الیاف کربن",
    weightBucket: "کمتر از ۵ کیلوگرم",
  },
  {
    id: "p6",
    name: "صفحه چدنی کلاسیک",
    price: 9_000_000,
    image: "/assets/cat-benches.jpg",
    engravable: true,
    category: "قدرتی",
    discipline: "پاورلیفتینگ",
    material: "چدن",
    weightBucket: "۵ تا ۱۵ کیلوگرم",
  },
  {
    id: "p7",
    name: "طناب پرش حرفه‌ای",
    price: 2_250_000,
    image: "/assets/latest-watch.jpg",
    category: "لوازم جانبی",
    discipline: "تمرین عملکردی",
    material: "چرم",
    weightBucket: "کمتر از ۵ کیلوگرم",
  },
  {
    id: "p8",
    name: "دمبل شش‌ضلعی",
    price: 11_000_000,
    image: "/assets/latest-dumbbells.jpg",
    engravable: true,
    category: "قدرتی",
    discipline: "تمرین عملکردی",
    material: "لاستیک",
    weightBucket: "۵ تا ۱۵ کیلوگرم",
  },
  {
    id: "p9",
    name: "دوچرخه ثابت حرفه‌ای",
    price: 95_000_000,
    image: "/assets/latest-bike.jpg",
    category: "هوازی",
    discipline: "دوچرخه‌سواری",
    material: "فولاد",
    weightBucket: "بالای ۳۰ کیلوگرم",
  },
  {
    id: "p10",
    name: "فوم رولر استودیو",
    price: 3_900_000,
    image: "/assets/latest-recovery.jpg",
    category: "ریکاوری",
    discipline: "تمرین عملکردی",
    material: "چوب پنبه",
    weightBucket: "کمتر از ۵ کیلوگرم",
  },
];
